"""
DocuSeal Service — Orchestrates e-sign submissions and template mapping.
"""

import json
import os
from typing import Any

import httpx

from structured_logging import logger as struct_logger

# Env vars (set in Cloud Run)
API_URL = os.environ.get("DOCUSEAL_API_URL", "")
API_TOKEN = os.environ.get("DOCUSEAL_API_TOKEN", "")
WEBHOOK_SECRET = os.environ.get("DOCUSEAL_WEBHOOK_SECRET", "")

# Local mapping file generated by tools/docuseal_template_uploader.py
MAPPING_FILE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "config",
    "docuseal_templates.json",
)

_template_cache: dict[str, dict[str, Any]] = {}


def _load_templates():
    """Load filename -> {id, fields} mapping from disk."""
    global _template_cache
    if _template_cache:
        return _template_cache

    if os.path.exists(MAPPING_FILE):
        try:
            with open(MAPPING_FILE, encoding="utf-8") as f:
                _template_cache = json.load(f)
        except Exception as e:
            struct_logger.error("Failed to load DocuSeal templates", error=str(e))
    return _template_cache


def get_template_id(filename: str) -> int | None:
    """Resolve a PDF filename to its DocuSeal template ID."""
    templates = _load_templates()
    entry = templates.get(filename)
    if entry:
        return entry.get("docuseal_template_id")
    return None


async def send_for_signature(
    *,
    email: str,
    name: str,
    template_name: str,
    deal_id: str | None = None,
    metadata: dict[str, Any] | None = None,
    values: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """
    Send a document for signature via DocuSeal.

    Returns a success/error dict.
    """
    if not API_URL or not API_TOKEN:
        return {
            "success": False,
            "status": "not_configured",
            "error": "DocuSeal API credentials not set",
        }

    # A template submission without values emails the buyer a blank contract.
    if not values:
        return {
            "success": False,
            "status": "missing_values",
            "error": "Refusing to send a signature request with no deal values filled in.",
        }

    template_id = get_template_id(template_name)
    if not template_id:
        # If not found in mapping, try using template_name as ID (backward compat)
        try:
            template_id = int(template_name)
        except (ValueError, TypeError):
            return {
                "success": False,
                "error": f"Template mapping not found for {template_name}",
            }

    payload = {
        "template_id": template_id,
        "send_email": True,
        "submitters": [
            {
                "role": "Buyer",
                "email": email,
                "name": name,
                "values": values or {},
            }
        ],
        "metadata": {
            "deal_id": deal_id,
            "template_name": template_name,
            **(metadata or {}),
        },
    }

    try:
        async with httpx.AsyncClient(timeout=15) as client:
            resp = await client.post(
                f"{API_URL.rstrip('/')}/api/submissions",
                headers={
                    "X-Auth-Token": API_TOKEN,
                    "Content-Type": "application/json",
                },
                json=payload,
            )
            if resp.status_code >= 400:
                error_detail = resp.text
                try:
                    error_detail = resp.json()
                except Exception:
                    pass
                struct_logger.error(
                    "DocuSeal API error",
                    status_code=resp.status_code,
                    detail=error_detail,
                    template=template_name,
                )
                return {
                    "success": False,
                    "error": f"DocuSeal API returned {resp.status_code}",
                    "detail": error_detail,
                }

            return {"success": True, "submission": resp.json()}
    except Exception as exc:
        struct_logger.error("DocuSeal submission failed", error=str(exc))
        return {"success": False, "error": str(exc)}


async def send_file_for_signature(
    *,
    email: str,
    name: str,
    file_path: str,
    display_name: str,
    deal_id: str | None = None,
    metadata: dict[str, Any] | None = None,
    include_esign_consent: bool = True,
) -> dict[str, Any]:
    """
    Upload a local PDF file to DocuSeal and send it for signature.

    Used for custom-generated packets that aren't fixed templates.

    When ``include_esign_consent`` is True (default), an ESIGN consumer-consent
    disclosure page is prepended as the first document so the signer affirmatively
    consents to electronic records/signatures before the substantive documents —
    required by 15 U.S.C. §7001(c). See esign_consent.py.
    """
    if not API_URL or not API_TOKEN:
        return {"success": False, "error": "DocuSeal credentials missing"}

    if not os.path.exists(file_path):
        return {"success": False, "error": f"File not found: {file_path}"}

    try:
        import base64

        with open(file_path, "rb") as f:
            file_content = base64.b64encode(f.read()).decode("utf-8")

        documents: list[dict[str, Any]] = []
        if include_esign_consent:
            try:
                from esign_consent import build_consent_document

                documents.append(build_consent_document())
            except Exception as consent_err:  # never let consent gen block signing
                struct_logger.warning(
                    "ESIGN consent page generation failed; sending without it",
                    error=str(consent_err),
                )
        documents.append({"name": display_name, "file": file_content})

        payload = {
            "send_email": True,
            "documents": documents,
            "submitters": [
                {
                    "role": "Buyer",
                    "email": email,
                    "name": name,
                }
            ],
            "metadata": {
                "deal_id": deal_id,
                "is_custom_file": True,
                "esign_consent_included": include_esign_consent and len(documents) > 1,
                **(metadata or {}),
            },
        }

        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                f"{API_URL.rstrip('/')}/api/submissions",
                headers={
                    "X-Auth-Token": API_TOKEN,
                    "Content-Type": "application/json",
                },
                json=payload,
            )
            if resp.status_code >= 400:
                return {
                    "success": False,
                    "error": f"DocuSeal API error {resp.status_code}",
                    "detail": resp.text,
                }

            return {"success": True, "submission": resp.json()}

    except Exception as exc:
        struct_logger.error("DocuSeal file submission failed", error=str(exc))
        return {"success": False, "error": str(exc)}


def is_configured() -> bool:
    """True when DocuSeal credentials are present, i.e. e-signing is live."""
    return bool(API_URL and API_TOKEN)


def submission_ids_from_response(submission: Any) -> list[str]:
    """Extract submission ids from a POST /api/submissions response.

    DocuSeal returns a list of submitters (each carrying ``submission_id``);
    some versions return a single submission object with ``id``.
    """
    items = submission if isinstance(submission, list) else [submission]
    ids: list[str] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        value = item.get("submission_id")
        if value is None and not isinstance(submission, list):
            value = item.get("id")
        if value is not None and str(value) not in ids:
            ids.append(str(value))
    return ids


async def archive_submission(submission_id: str) -> dict[str, Any]:
    """Cancel a pending signing request via DocuSeal's archive API.

    ``DELETE /api/submissions/{id}`` archives the submission, which stops the
    signer from completing it.
    """
    if not is_configured():
        return {
            "success": False,
            "status": "not_configured",
            "error": "DocuSeal API credentials not set",
        }
    safe_id = str(submission_id or "").strip()
    if not safe_id.isdigit():
        return {"success": False, "error": "Invalid submission id"}

    try:
        async with httpx.AsyncClient(timeout=15) as client:
            resp = await client.delete(
                f"{API_URL.rstrip('/')}/api/submissions/{safe_id}",
                headers={"X-Auth-Token": API_TOKEN},
            )
        if resp.status_code >= 400:
            struct_logger.error(
                "DocuSeal archive failed",
                status_code=resp.status_code,
                submission_id=safe_id,
            )
            return {"success": False, "error": f"DocuSeal API returned {resp.status_code}"}
        return {"success": True}
    except Exception as exc:
        struct_logger.error("DocuSeal archive request failed", error=str(exc))
        return {"success": False, "error": str(exc)}
